---
# First, define a default "Service"
apiVersion: v1
kind: Service
metadata:
  name: foobar
  namespace: {{ .Values.name }}
spec:
  ports:
    - port: 8080
  selector:
    app: {{ .Values.name }}
---
kind: Ingress
metadata:
  name: default-ingress
  namespace: {{.Values.name}}
  annotations:
    # This line is required:
    kubernetes.io/ingress.class: "nginx"
    # Our application serves at "/", so we simply remove the prefix:
    ingress.kubernetes.io/rewrite-target: "/"
    # If you need your service to be accessible only to our office or to certain IPs, use this:
    ingress.kubernetes.io/whitelist-source-range: "127.0.0.1/32"
spec:
  rules:
  - http:
      paths:
      # expose foobar as /foobar/
      - path: /{{ .Values.name }}/
        backend:
          serviceName: foobar
          servicePort: 8080
